map_box: [9.460272477856407, -2.6993474938850515, 1.0, 1.0, 0.0, -3.817007622081654,
  -7.5817523083874345, 1.0, 1.0, 0.0, 8.315314080815792, -7.290435886369961, 1.0,
  1.0, 0.0, -3.3576421634331854, 7.949597847997683, 1.0, 1.0, 0.0, -0.007024443054532981,
  2.305764844301134, 1.0, 1.0, 0.0, -9.41335314491276, 0.5576537547729465, 1.0, 1.0,
  0.0, -9.358543071600291, 6.542846456726291, 1.0, 1.0, 0.0, -5.078608657878032, 1.629825047362651,
  1.0, 1.0, 0.0, 3.6295702839242487, 1.972570532664692, 1.0, 1.0, 0.0, 2.3570117427855752,
  -8.595729520260832, 1.0, 1.0, 0.0, -8.614420548639973, -7.279852227598207, 1.0,
  1.0, 0.0, 5.777826393140176, -8.152030841523407, 1.0, 1.0, 0.0, -5.2426241598538725,
  -5.127041747664305, 1.0, 1.0, 0.0, 3.963995323591325, 4.674842665265624, 1.0, 1.0,
  0.0, -9.604706725423659, 9.285834605991187, 1.0, 1.0, 0.0, -4.1962886673426585,
  5.090732794325897, 1.0, 1.0, 0.0, 1.162361027179431, -1.4441480890308789, 1.0, 1.0,
  0.0, 7.967526500112619, 4.56888067915572, 1.0, 1.0, 0.0, 9.095097407527405, -4.645049271198076,
  1.0, 1.0, 0.0, -8.628353028890887, -4.011992268782702, 1.0, 1.0, 0.0, 1.8316706831273422,
  -5.934017092873274, 1.0, 1.0, 0.0, 5.919099711122538, -5.332524638568654, 1.0, 1.0,
  0.0, 0.3153130639182873, 6.756813817404684, 1.0, 1.0, 0.0, 8.415802159974092, -0.035441410892882885,
  1.0, 1.0, 0.0, -2.0716292887654664, -1.5848863330301572, 1.0, 1.0, 0.0, -8.16256333457001,
  -1.9582276192590715, 1.0, 1.0, 0.0, -7.380518272696673, 6.674578962461311, 1.0,
  1.0, 0.0, 6.009367497981248, 8.357601839972787, 1.0, 1.0, 0.0, -7.253926831082458,
  0.09464635114897213, 1.0, 1.0, 0.0, -1.9008303976540546, -6.528556769305656, 1.0,
  1.0, 0.0, 3.8974642237416504, -1.7715634522447026, 1.0, 1.0, 0.0, 6.028834755550694,
  -3.0699601887384524, 1.0, 1.0, 0.0, -9.118417430646069, 3.734400369616056, 1.0,
  1.0, 0.0, -1.8226218391565787, 4.16021788128106, 1.0, 1.0, 0.0, 4.00085339059239,
  -5.70975507672018, 1.0, 1.0, 0.0, -6.753506159349936, -9.88693863746309, 1.0, 1.0,
  0.0, -1.5786129527623611, -8.863736380527351, 1.0, 1.0, 0.0, 5.539858114120575,
  0.038068383074874035, 1.0, 1.0, 0.0, 0.47184089422321307, -4.0236917978595566, 1.0,
  1.0, 0.0, -3.178700621815425, 0.8270786661540885, 1.0, 1.0, 0.0, -0.5276411580223126,
  8.99412707007065, 1.0, 1.0, 0.0, -5.116542129859498, -1.4207929244398514, 1.0, 1.0,
  0.0, 9.441783234256832, -9.370801288817683, 1.0, 1.0, 0.0, 6.1293360758666715, 2.027975105056184,
  1.0, 1.0, 0.0, 5.792409302460769, 5.9837007008863115, 1.0, 1.0, 0.0, -3.2048567169787052,
  -4.253007809698481, 1.0, 1.0, 0.0, 3.584393107880139, 9.187611626141724, 1.0, 1.0,
  0.0, 1.3486011234384172, 9.375553258858154, 1.0, 1.0, 0.0, 9.704926249024059, 2.1751741466880716,
  1.0, 1.0, 0.0, 3.698169892582923, 6.785072301191921, 1.0, 1.0, 0.0, -6.41261809432047,
  -7.812775805644239, 1.0, 1.0, 0.0, 8.103166761832739, 7.527020078450011, 1.0, 1.0,
  0.0, 9.995851288895032, 7.285093721141671, 1.0, 1.0, 0.0, 9.042506177559854, 9.517079418643842,
  1.0, 1.0, 0.0, 0.39833649580802444, -8.923513956997592, 1.0, 1.0, 0.0, -4.451225620890165,
  -9.87784393946802, 1.0, 1.0, 0.0, -5.67447589126981, 9.526690295588399, 1.0, 1.0,
  0.0, -6.028738556586946, 3.449019273952967, 1.0, 1.0, 0.0, -5.871379558523831, -3.2279264944523423,
  1.0, 1.0, 0.0, 1.1366106826399118, 4.240504982698884, 1.0, 1.0, 0.0, 6.04474032059867,
  4.162267528134933, 1.0, 1.0, 0.0, -7.620492346526411, 8.530651778626893, 1.0, 1.0,
  0.0, -2.3395979187059375, 9.823874951375977, 1.0, 1.0, 0.0, -0.09135182419280419,
  -6.679752458394141, 1.0, 1.0, 0.0, 6.695366231654436, -9.953024886405025, 1.0, 1.0,
  0.0]
map_size: [-10.0, 10.0, -10.0, 10.0]
